[tool.black]
line-length = 80
target-version = ['py39']
exclude = '/.*(__pycache__).*/'

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "spych"
version = "2.0.0"
description = "Communicate with your favorite AI model by talking to it."
authors = [
    {name="Connor Makowski", email="conmak@mit.edu"}
]
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    'License :: OSI Approved :: MIT License',
    "Operating System :: OS Independent",
]
dependencies = ["faster-whisper==1.2.1", "pvrecorder", "numpy"]

[project.urls]
"Homepage" = "https://github.com/connor-makowski/spych"
"Bug Tracker" = "https://github.com/connor-makowski/spych/issues"
"Documentation" = "https://connor-makowski.github.io/spych/spych/index.html"